# Define the pins that are inputs or outputs.
directions:
  '4': out
  '5': out
  '6': out
  '12': out
  '13': out
  '17': out
  '18': out
  '22': out
  '23': out
  '24': out
  '25': out
  '26': out
  '27': out

# Define default pin states.
states:
  '4': 1
  '5': 1
  '6': 1
  '12': 1
  '13': 1
  '17': 1
  '18': 1
  '22': 1
  '23': 1
  '24': 1
  '25': 1
  '26': 1
  '27': 1

shutdown_states:
  '4': 0
  '5': 0
  '6': 0
  '12': 0
  '13': 0
  '17': 0
  '18': 0
  '22': 0
  '23': 0
  '24': 0
  '25': 0
  '26': 0
  '27': 0
